[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/mb/"
  status = 302

[[redirects]]
  from = "/mb"
  to = "/mb/"
  status = 301

[[redirects]]
  from = "/iran"
  to = "/iran/"
  status = 301

[[redirects]]
  from = "/iums"
  to = "/iums/"
  status = 301

[[redirects]]
  from = "/sevenspikes"
  to = "/sevenspikes/"
  status = 301

[[redirects]]
  from = "/expanded-mb-names"
  to = "/expanded-mb-names/"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "https://165.232.35.81.sslip.io/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "https://165.232.35.81.sslip.io/health"
  status = 200

[[redirects]]
  from = "/generated-graphs/*"
  to = "https://165.232.35.81.sslip.io/generated-graphs/:splat"
  status = 200
